In [1]:
# Import
import pandas as pd
from pathlib import Path

In [2]:
# Read in CSV file with Exchange-Coin data
#manually changed between Bitfinex, Gemini and all coins
df = pd.read_csv(Path("./USD_pairs/Gemini/daily/Gemini_BTCUSD_d.csv"), parse_dates= True, infer_datetime_format = True)
df.head()

                                                                                           https://www.CryptoDataDownload.com
unix          date                symbol  open     high     low      close    Volume BTC                           Volume USD
1672200000000 2022-12-28 04:00:00 BTC/USD 16654.4  16740.0  16461.84 16547.26 822.36680139                  13607917.27796869
1672113600000 2022-12-27 04:00:00 BTC/USD 16860.53 16887.51 16567.02 16654.4  577.64459251                  9620324.101498546
1672027200000 2022-12-26 04:00:00 BTC/USD 16886.24 16966.0  16797.1  16860.53 255.3095308                   4304654.003339324
1671940800000 2022-12-25 04:00:00 BTC/USD 16835.6  16894.34 16680.0  16886.24 152.1216333                  2568762.4090957926

In [3]:
# reformat the dataframe to include OHLCV data for years 2021-2022
df = df.reset_index()
df.rename(columns = {"level_0":"Unix", "level_1": "Datetime", "level_2": "Symbol_Pair",
                        "level_3": "Open", "level_4": "High", "level_5": "Low", "level_6": "Close",
                        "level_7": "Volume_in_BTC", "https://www.CryptoDataDownload.com": "Volume_USD"},
              inplace = True)
df = df.drop([0,1], axis=0)
df = df.drop(["Unix"], axis=1)
df = df.set_index("Datetime")

In [4]:
df.index = pd.to_datetime(df.index)
df.insert(loc=0, column = "Exchange", value= "Gemini")

In [5]:
display(df.head(5))
df.tail()

,Exchange,Symbol_Pair,Open,High,Low,Close,Volume_in_BTC,Volume_USD
Datetime,,,,,,,,
2022-12-27 04:00:00,Gemini,BTC/USD,16860.53,16887.51,16567.02,16654.4,577.64459251,9620324.101498546
2022-12-26 04:00:00,Gemini,BTC/USD,16886.24,16966.0,16797.1,16860.53,255.3095308,4304654.003339324
2022-12-25 04:00:00,Gemini,BTC/USD,16835.6,16894.34,16680.0,16886.24,152.1216333,2568762.4090957926
2022-12-24 04:00:00,Gemini,BTC/USD,16848.0,16874.5,16806.35,16835.6,145.59193897,2451127.6477233316
2022-12-23 04:00:00,Gemini,BTC/USD,16828.96,16935.48,16750.99,16848.0,363.17435522,6118761.53674656

,Exchange,Symbol_Pair,Open,High,Low,Close,Volume_in_BTC,Volume_USD
Datetime,,,,,,,,
2015-10-12 04:00:00,Gemini,BTC/USD,248.98,248.98,245.75,245.75,71.0477426014,17459.98274429405
2015-10-11 04:00:00,Gemini,BTC/USD,246.3,249.5,245.96,248.98,22.7470905831,5663.570613380238
2015-10-10 04:00:00,Gemini,BTC/USD,245.51,246.3,244.6,246.3,30.8705493027,7603.41629325501
2015-10-09 04:00:00,Gemini,BTC/USD,243.6,249.97,243.6,245.51,61.5870675401,15120.24095176995
2015-10-08 04:00:00,Gemini,BTC/USD,0.0,245.0,0.0,243.6,34.7547026012,8466.24555365232

In [6]:
# check data types
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2638 entries, 2022-12-27 04:00:00 to 2015-10-08 04:00:00
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Exchange       2638 non-null   object
 1   Symbol_Pair    2638 non-null   object
 2   Open           2638 non-null   object
 3   High           2638 non-null   object
 4   Low            2638 non-null   object
 5   Close          2638 non-null   object
 6   Volume_in_BTC  2638 non-null   object
 7   Volume_USD     2638 non-null   object
dtypes: object(8)
memory usage: 185.5+ KB

In [7]:
# change data type to string and float
df = df.astype({'Symbol_Pair': str})
columns = ['Open', 'High', 'Low', 'Close', 'Volume_USD', 'Volume_in_BTC']
for c in columns:
    df = df.astype({c: float})

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2638 entries, 2022-12-27 04:00:00 to 2015-10-08 04:00:00
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Exchange       2638 non-null   object
 1   Symbol_Pair    2638 non-null   object
 2   Open           2638 non-null   float64
 3   High           2638 non-null   float64
 4   Low            2638 non-null   float64
 5   Close          2638 non-null   float64
 6   Volume_in_BTC  2638 non-null   float64
 7   Volume_USD     2638 non-null   float64
dtypes: float64(6), object(2)
memory usage: 185.5+ KB

In [9]:
df.isna().sum().sum()

0

In [10]:
df = df.loc['2021-01-01':'2022-12-27']
display(df.head())
df.tail()

/opt/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Value based partial slicing on non-monotonic DatetimeIndexes with non-existing keys is deprecated and will raise a KeyError in a future Version.
  """Entry point for launching an IPython kernel.

,Exchange,Symbol_Pair,Open,High,Low,Close,Volume_in_BTC,Volume_USD
Datetime,,,,,,,,
2022-12-26 04:00:00,Gemini,BTC/USD,16886.24,16966.00,16797.10,16860.53,255.309531,4.304654e+06
2022-12-25 04:00:00,Gemini,BTC/USD,16835.60,16894.34,16680.00,16886.24,152.121633,2.568762e+06
2022-12-24 04:00:00,Gemini,BTC/USD,16848.00,16874.50,16806.35,16835.60,145.591939,2.451128e+06
2022-12-23 04:00:00,Gemini,BTC/USD,16828.96,16935.48,16750.99,16848.00,363.174355,6.118762e+06
2022-12-22 04:00:00,Gemini,BTC/USD,16859.25,16880.96,16558.44,16828.96,906.337362,1.525272e+07

,Exchange,Symbol_Pair,Open,High,Low,Close,Volume_in_BTC,Volume_USD
Datetime,,,,,,,,
2021-01-06 04:00:00,Gemini,BTC/USD,34228.19,37824.48,33685.82,37613.11,4924.996219,1.852444e+08
2021-01-05 04:00:00,Gemini,BTC/USD,31203.46,34536.29,29914.50,34228.19,3056.563067,1.046206e+08
2021-01-04 04:00:00,Gemini,BTC/USD,33617.30,33669.00,27632.34,31203.46,4603.921519,1.436583e+08
2021-01-03 04:00:00,Gemini,BTC/USD,32637.23,34776.00,32301.61,33617.30,2175.138861,7.312230e+07
2021-01-02 04:00:00,Gemini,BTC/USD,29441.14,33309.76,29313.31,32637.23,3684.936682,1.202661e+08

In [11]:
df_export = df.copy()
df_export.to_csv('./Data/Gemini/21-22Gemini_BTC_d.csv')